apiVersion: v1
kind: Pod
metadata:
  name: error-test
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: error-test
spec:
  containers:
    - name: nginx
      image: nginxssdfcdefy
