apiVersion: v1
kind: Pod
metadata:
  name: annotations-test
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: annotations
  annotations:
    jenkins.url: jenkins.io
    jenkins.common.path: "/var/jenkins"
spec:
  containers:
    - name: nginx
      image: nginx
