apiVersion: v1
kind: Secret
metadata:
  name: secret-test
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: env
data:
  username: "YWRtaW4tZHlubwo=" #encoded using base64
  password: "RHlub0Rldk9wczEyMwo="
