apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: env
  spec:
    containers:
      - name: nginx
        image: nginx
        envFrom:
          - secretRef:
              name: secret-test
