apiVersion: v1
kind: Service
metadata:
  name: service-nodePort
  namespace: roboshop
spec:
  type: NodePort
  selector:
    project: roboshop
    component: frontend
    environment: dev
    purpose: NodePort
  ports:
    - protocol: TCP
      port: 80 #servicePort
      targetPort: 80 #containerPort
