apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-headless
  labels:
    purpose: headless
    environment: dev
  namespace: roboshop
spec:
  # Specify replicas to be created
  replicas: 3
  selector:
    matchLabels:
      purpose: headless
      environment: dev
  template:
    # pod definition
    metadata:
      labels:
        purpose: headless
        environment: dev
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: service-test
  namespace: roboshop
spec:
  selector:
    purpose: headless
    environment: dev
  ports:
    - protocol: TCP
      port: 80 #servicePort
      targetPort: 80 #containerPort

---
apiVersion: v1
kind: Service
metadata:
  name: service-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    purpose: headless
    environment: dev
  ports:
    - protocol: TCP
      port: 80 #servicePort
      targetPort: 80 #containerPort
