apiVersion: v1
kind: Service
metadata:
  name: stateful-test
  namespace: roboshop
spec:
  selector:
    purpose: headless
    environment: dev
  ports:
    - protocol: TCP
      port: 80 #servicePort
      targetPort: 80 #containerPort

---
apiVersion: v1
kind: Service
metadata:
  name: stateful-test
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    purpose: headless
    environment: dev
  ports:
    - protocol: TCP
      port: 80 #servicePort
      targetPort: 80 #containerPort
