apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::055610219795:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-8HyDS9j3JknD
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
        - roboshop-trainee
      userarn: arn:aws:iam::055610219795:user/chikoo
      username: chikoo
kind: ConfigMap
metadata:
  creationTimestamp: "2026-10-04T09:20:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1175"
  uid: 0e247833-7373-449c-b26a-6d796523f2b4
