apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-pod
  namespace: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /var/log/nginx
          name: nginx-logs
    - name: almalinux
      image: almalinux:9
      command:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: /mnt/nginx-log
          name: nginx-logs
  volumes:
    - name: empty-dir-volume
      emptyDir:
        sizeLimit: "100Mi"
