apiVersion: v1
# containers inside a pod can share data using emptyDir volume.
#When a Pod is removed from a node for any reason, the data in the emptyDir is deleted forever.
kind: Pod
metadata:
  name: empty-dir-pod
  namespace: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /var/log/nginx
          name: nginx-logs
    - name: almalinux
      image: almalinux:9
      command:
        - sleep
        - "10000"
      volumeMounts:
        - mountPath: /mnt/nginx-log
          name: nginx-logs
          readOnly: true
  volumes:
    - name: empty-dir-volume
      emptyDir:
        sizeLimit: "100Mi"
