apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-test-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-061137b2a12beddbe #EFS File System ID

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-test-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-efs-static
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: nginx-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-storage
      persistentVolumeClaim:
        claimName: efs-test-claim
