kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic-test
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-00af77c5d2f1fc37f
  directoryPerms: "700"
  basePath: "/roboshop"
